### ISSUE TITLE
Clean up src/Makefile

### ISSUE THREAD

**Issue by DanGiles** [UCL/swiftsim#12]
Sort out the issue of SCOTCH_LIBS and SCOTCH_INCS not being added to the src/Makefile

**Comment by themkots** [comment]
Solved by 
commit 151a7e9b831bb248b7d3aaeba4607c3375f887ac
Author: Euthymios Kotsialos <dc-kots1@login8a.pri.cosma7.alces.network>
Date:   Fri Aug 11 11:35:26 2023 +0100

    Added SCOTCH_LIBS, SCOTCH_INCS to src/Makefile.am for Scotch MPI compilation.
