### ISSUE TITLE
Working example with Scotch and single Node

### ISSUE THREAD

**Issue by DanGiles** [UCL/swiftsim#8]
In order to get a first working example of the process mapping, the suggested solution will involve the use of `SCOTCH_graphMap`. The documentation for scotch can be found [here](https://github.com/live-clones/scotch/blob/master/doc/scotch_user7.0.pdf). As the documentation states we will need to pass three inputs: the source graph structure (virtual topology), the target architecture (hardware topology) and the mapping strategy. Starting small we can use the EAGLE_6 test case.

The three inputs:
- [x] source graph structure - this can be constructed from the information within swift. To avoid running swift in the development we should read in the output from `dumpMETISGraph`. 
- [x] target architecture structure - as we will test on one node first we can use hwloc to derive the information on the NUMA regions etc. and pipe this into a SCOTCH struct.
- [x] mapping strategy - we are free to play around with the various inbuilt mapping strategies.

To test this we can compare the output with the METIS partitioning which is already carried out in swift.

**Comment by themkots** [comment]
Probable implementation of the Adjacency matrix will utilise sparse matrix representations, instead of a NxN mostly empty matrix:
https://www.geeksforgeeks.org/sparse-matrix-representation/

**Comment by themkots** [comment]
* uncomment the two functions to dump METIS and parMETIS graphs, upon calling the `dumpCellRanks` function
![image](https://user-images.githubusercontent.com/70752441/224361338-ff25123e-e163-498d-9b1d-d4326281cfce.png)


* for the `low_z/EAGLE_6` dataset, use, e.g., this jobscript; this will generate METIS and PARMETIS dumps of the graphs at various points in the computation

`[ucaseko@login12.myriad:230 EAGLE_6]$ cat eagle_6_sge_myriad_mpi.sh`
`#!/bin/bash -l`
`# Batch script to run an MPI parallel job under SGE with Intel MPI.`
`# Request ten minutes of wallclock time (format hours:minutes:seconds).`
`#$ -l h_rt=02:00:0`
`# Request 1 gigabyte of RAM per process (must be an integer followed by M, G, or T)`
`#$ -l mem=1G`
`# Request 15 gigabyte of TMPDIR space per node`
`# (default is 10 GB - remove if cluster is diskless)`
`#$ -l tmpfs=15G`
`# Set the name of the job.`
`#$ -N EAGLE_6`
`# Request N mpi ranks.`
`#$ -pe mpi 36`
`export OMP_NUM_THREADS=18`
`# Set the working directory to somewhere in your scratch space.`
`# Replace "<your_UCL_id>" with your UCL user ID :`
`#$ -wd /home/ucaseko/Scratch/swiftsim/examples/EAGLE_low_z/EAGLE_6`
`module add fftw/3.3.4-impi/intel-2017-update1`
`module add numactl/2.0.12`
`module add hwloc/1.11.12`
`module add parmetis/4.0.3/intel-2015-update2`
`module add gsl/2.4/intel-2017`
`module add metis/5.1.0/intel-2018`
`module add hdf/5-1.10.2-impi/intel-2018`
`# Run our MPI job.  GERun is a wrapper that launches MPI jobs on our clusters.`
`#cat /proc/cpuinfo`
`#mpirun -n 2 ../../../swift_mpi  --cosmology --hydro --self-gravity --stars --threads=18 --pin eagle_6.yml 2>&1 | tee output.log`
`gerun /home/ucaseko/Scratch/swiftsim/swift_mpi --cosmology --hydro --self-gravity --stars --threads=18 eagle_6.yml 2>&1 | tee output.log`


![image](https://user-images.githubusercontent.com/70752441/224362735-a1882ef7-5e02-4c3e-be9b-88e5787ff6ef.png)

Of those, the files `parmetis_graph_std_xxx.dat` are of immediate use in constructing the adjacency matrix; have to clarify what exactly are the right-side numbers in the pairs (row_number, number) -- ? number of mpi messages? -- will find out
There are also weights in the similarly constructed files `parmetis_graph_weights_xxx.dat` -- will look in how to utilise them as well.

**Comment by themkots** [comment]
`module` environment to use in `Myriad` (used in producing the above):
`module load gcc-libs/4.9.2 cmake/3.21.1 flex/2.5.39 git/2.32.0  gerun nano/2.4.2  dos2unix/7.3 giflib/5.1.1 userscripts/1.4.0  default-modules/2018 python/3.8.0  compilers/intel/2018/update3 mpi/intel/2018/update3/intel fftw/3.3.4-impi/intel-2017-update1 numactl/2.0.12 hwloc/1.11.12 parmetis/4.0.3/intel-2015-update2 gsl/2.4/intel-2017 metis/5.1.0/intel-2018 hdf/5-1.10.2-impi/intel-2018`

**Comment by themkots** [comment]
in `Myriad`, I had to 'flatten' the hdf5 data, as downloaded from the main repo, otherwise `swiftsim` complains.
So, e.g., 
`mv EAGLE_ICs_25.hdf5 EAGLE_ICs_25.hdf5.deflated`
`h5repack -f NONE -i EAGLE_ICs_25.hdf5.deflated -o EAGLE_ICs_25.hdf5`

**Comment by themkots** [comment]
I was worried about two things in the parmetis dumps:
* how the number of n^2 elements will scale in the n x n representation of the square adjacency matrix; it goes as eagle_6 -> 512, eagle_25 -> 1728 
* how many neighboring cells interact at every dumped row; this seems constant for eagle_6 and eagle_25 (both low_z, so more investigation is needed)
`awk '{ print NF; }' parmetis_graph_std_001.dat | sort -u` gives in both cases `4,53`, 4 for 1st line, and all others are 53.

**Comment by DanGiles** [comment]
- Regarding the dumps, each vertex has exactly 26 neighbours this is why you see a constant in both eagle runs.
- The `parmetis_graph_std_xxx.dat` contains both the vertex indices of neighbours and the edge weights. The `parmetis_graph_simple_xxx.dat`contains just the neighbour vertices and `parmetis_graph_weights_xxx.dat` is the vertex and edge weights
