### ISSUE TITLE
MPI probe to detect physical topology

### ISSUE THREAD

**Issue by DanGiles** [UCL/swiftsim#9]
- Write a MPI_detect_env.sh to return a config file which will contain the physical topology.
- This config file can be passed to the swift executable
- Can also be used for comparing with hwloc graph initialisation

**Comment by themkots** [comment]
Desired switches to drive the detection:
* number of nodes to use
* mpi ranks => number of NUMA regions
* threads?

Use info from 

`lscpu | grep -i numa`
`numactl -s`
`ssh` to a specific node and pass / execute say `numactl`



Objective:
1) Adjacency matrix with the comms costs for all NUMA regions, for all mpi ranks
2) 

Approaches:
1) 'naive' - direct using 
2) send mpi tasks out to be executed - log info - get back results using relevant mpi_*() calls
